/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-03 07:39:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class new_005flogin_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/yourcode.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.slim.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(() => {\r\n");
      out.write("      console.log(\"login script working fine....\")\r\n");
      out.write("      $(\"#reg_submit\").click(() => {\r\n");
      out.write("\r\n");
      out.write("        console.log(\"click on register_submit...\")\r\n");
      out.write("\r\n");
      out.write("        if ($(\"#fname\").val() != \"\" && $(\"#lname\").val() != \"\" && $(\"#emailID\").val() != \"\" && $(\"#password\").val() && $(\"#Confirmed_Pass\").val() != \"\") {\r\n");
      out.write("\r\n");
      out.write("          let input = {\r\n");
      out.write("            password: $(\"#password\").val(),\r\n");
      out.write("            Confirmed_Pass: $(\"#Confirmed_Pass\").val()\r\n");
      out.write("          }\r\n");
      out.write("          console.log(input.password)\r\n");
      out.write("          console.log(input.Confirmed_Pass)\r\n");
      out.write("          console.log(input.password !== input.Confirmed_Pass)\r\n");
      out.write("\r\n");
      out.write("          if (input.password !== input.Confirmed_Pass) {\r\n");
      out.write("            alert(\"Password doest not match with the confirmed password, Please enter correct one!\")\r\n");
      out.write("          } \r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("          alert(\"Please enter the correct details, input can not be blank!\")\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      })\r\n");
      out.write("\r\n");
      out.write("    })\r\n");
      out.write("  </script>\r\n");
      out.write("<title>DigiRozgar - You are one step away from getting a job for\r\n");
      out.write("	a day!</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background:url(Img/bg-2.jpg); background-size:cover;\">\r\n");
      out.write("	<!-- ========== header ============ -->\r\n");
      out.write("\r\n");
      out.write("	<header id=\"header\">\r\n");
      out.write("		<div class=\"container search_job_header\">\r\n");
      out.write("			<div class=\"row breakcrum_row\">\r\n");
      out.write("				<nav aria-label=\"breadcrumb\">\r\n");
      out.write("					<ol class=\"breadcrumb\">\r\n");
      out.write("						<li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("						<li class=\"breadcrumb-item active\">Login</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"container\" id=\"login-page\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-4 col-md-6 offset-lg-4 offset-md-3\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-6\">\r\n");
      out.write("								<h6 id=\"login-bar\" class=\"lead\">Login</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-6\">\r\n");
      out.write("								<h6 id=\"reg-bar\" class=\"lead\">Register</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row flex-nowrap\" id=\"login-page-toggle\">\r\n");
      out.write("							<div class=\"col-12\" id=\"old_user_login\">\r\n");
      out.write("\r\n");
      out.write("								<form action=\"login\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"row text-center\">\r\n");
      out.write("										<label for=\"\">Log In as</label>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"role\"\r\n");
      out.write("										value=\"employer\"> <label class=\"form-check-label\">\r\n");
      out.write("										Employer </label> <input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("										name=\"role\" value=\"employee\"> <label\r\n");
      out.write("										class=\"form-check-label\">Employee </label> <br> <label\r\n");
      out.write("										for=\"\">user ID</label> <input type=\"text\" name=\"userID\"\r\n");
      out.write("										placeholder=\"User ID\" class=\"form-control\" required> <br>\r\n");
      out.write("									<label for=\"\">Password</label> <input type=\"password\"\r\n");
      out.write("										name=\"password\" placeholder=\"secret key\" class=\"form-control\"\r\n");
      out.write("										required>\r\n");
      out.write("									<!-- <span id=\"forget-pass\" disabled=\"\"><a href=\"forgetPass.html\">forgot password?</a></span> -->\r\n");
      out.write("									<span> <input type=\"checkbox\" name=\"rememberMe\"\r\n");
      out.write("										value=\"yes\"> Remember Me \r\n");
      out.write("									</span><br> <span id=\"update-pass\"><a\r\n");
      out.write("										href=\"updatePass.html\">Forgot Password?</a></span> <br>\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-3 offset-5\">\r\n");
      out.write("											<input type=\"submit\" value=\"login\"> <br>\r\n");
      out.write("								</form>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-12\" id=\"reg_new_user\">\r\n");
      out.write("						<form action=\"user-registration\" method=\"post\">\r\n");
      out.write("							<div id=\"register_from\">\r\n");
      out.write("								<label for=\"\">First Name</label> <input type=\"text\" name=\"fname\"\r\n");
      out.write("									id=\"fname\" placeholder=\"Please enter your First Name\"\r\n");
      out.write("									class=\"form-control\" required> <label for=\"\">Last\r\n");
      out.write("									Name</label> <input type=\"text\" name=\"lname\" id=\"lname\"\r\n");
      out.write("									placeholder=\"Please enter your last Name\" class=\"form-control\"\r\n");
      out.write("									required> <label for=\"\">Email ID</label> <input\r\n");
      out.write("									type=\"email\" name=\"emailID\" id=\"emailID\" placeholder=\"email id\"\r\n");
      out.write("									class=\"form-control\" required> <label for=\"\">Choose\r\n");
      out.write("									Your Role</label>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"role\"\r\n");
      out.write("										value=\"employer\"> <label class=\"form-check-label\">\r\n");
      out.write("										Employer </label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-check\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"role\"\r\n");
      out.write("										value=\"employee\"> <label class=\"form-check-label\">\r\n");
      out.write("										Employee </label>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<label for=\"\">Create Password</label> <input type=\"password\"\r\n");
      out.write("									name=\"password\" id=\"password\" placeholder=\"password\"\r\n");
      out.write("									class=\"form-control\" required>\r\n");
      out.write("								<!-- <span id=\"forget-pass\">your password must have at least 8 characters</span> -->\r\n");
      out.write("								<label for=\"\">Confirm Password</label> <input type=\"password\"\r\n");
      out.write("									id=\"Confirmed_Pass\" name=\"Confirmed_Pass\"\r\n");
      out.write("									placeholder=\"Confirm password\" class=\"form-control\" required>\r\n");
      out.write("								<br>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-3 offset-5\">\r\n");
      out.write("										<input type=\"submit\" id=\"reg_submit\" value=\"signUp\"> <br>\r\n");
      out.write("										<br>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- ================ main ============= -->\r\n");
      out.write("	<!-- ============== nav_menu ============ -->\r\n");
      out.write("	<div class=\"nav_menu navigation\" id=\"nav-menu\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3 justify-content-space-between\">\r\n");
      out.write("				<div class=\"row title-bar\">\r\n");
      out.write("					<div class=\"col-9\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a class=\"title\" href=\"index.html\">DigiRozgar</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-3 d-sm-none\" id=\"menu-icon\">\r\n");
      out.write("						<i class=\"fa fa-list\" id=\"menu_toggle\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-9\">\r\n");
      out.write("				<nav class=\"row\">\r\n");
      out.write("					<div class=\"col-sm-7\">\r\n");
      out.write("						<ul class=\"nav_bar\">\r\n");
      out.write("							<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("							<li><a href=\"about.html\">About</a></li>\r\n");
      out.write("							<li><a href=\"blog.html\">Blog</a></li>\r\n");
      out.write("							<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("							<li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-sm-5\">\r\n");
      out.write("						<a href=\"postjob.html\" class=\"btn bg-primary text-light\">Post\r\n");
      out.write("							a Job</a> <a href=\"index.html\" class=\"btn bg-success text-light\">Search\r\n");
      out.write("							a Job</a> <a href=\"adminlogin.jsp\" class=\"btn bg-success text-light\">Admin\r\n");
      out.write("							Login</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ==================== Footer ================== -->\r\n");
      out.write("\r\n");
      out.write("	<footer id=\"footer\">\r\n");
      out.write("		<div class=\"container footer\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("					<h3>About</h3>\r\n");
      out.write("					<p>We aim to provide job for a day for every individual who is\r\n");
      out.write("						looking out for an Job!</p>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#facebook\">facebook</a></li>\r\n");
      out.write("						<li><a href=\"#Twitter\">Twitter</a></li>\r\n");
      out.write("						<li><a href=\"#Instagram\">Instagram</a></li>\r\n");
      out.write("						<li><a href=\"#Yotube\">YouTube</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("					<h5>Employers</h5>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"\">Register</a></li>\r\n");
      out.write("						<li><a href=\"\">Post a Job</a></li>\r\n");
      out.write("						<li><a href=\"\">Advance Skill Search</a></li>\r\n");
      out.write("						<li><a href=\"\">Recruiting Service</a></li>\r\n");
      out.write("						<li><a href=\"\">Blog</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("					<h5>Workers</h5>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"\">Register</a></li>\r\n");
      out.write("						<li><a href=\"\">Post Your Skills</a></li>\r\n");
      out.write("						<li><a href=\"\">Job Search</a></li>\r\n");
      out.write("						<li><a href=\"\">Emploer Search</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("					<h5>Have a question?</h5>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"\"> 203, Ramsan Road, BKC Complex, Mumbai,\r\n");
      out.write("								India</a></li>\r\n");
      out.write("						<li><a href=\"\">+91 02292 3929 210</a></li>\r\n");
      out.write("						<li><a href=\"\">info@jobportal.com</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"js/main.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
